version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: homepromise_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: homepromise_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    ports:
      - 5432:5432
    env_file:
      - ./.env

  # redis:
  #   image: redis:latest

  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   image: homepromise_celery_worker
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - redis
  #     - db

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   image: homepromise_celery_beat
  #   command: /start-celerybeat
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - redis
  #     - db

  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   image: homepromise_celery_flower
  #   command: /start-flower
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #     - db

volumes:
  postgres_data:
  postgres_data_backups: